name: Deploy Services

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Payment Handling Service
      run: |
        cd payment-handling-service
        ./mvnw clean package -DskipTests

    - name: Build Core Banking Service
      run: |
        cd core-banking-service
        ./mvnw clean package -DskipTests

    - name: Build Docker images
      run: |
        cd payment-handling-service
        docker build -t yourusername/paymenthandlingservice:latest .
        
        cd ../core-banking-service
        docker build -t yourusername/corebankingservice:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images
      run: |
        docker push rajivnjit/paymenthandlingservice:latest
        docker push rajivnjit/corebankingservice:latest
